### PR TITLE
Add Pikmin 3 server hosting

### PR DESCRIPTION
**Pull request by ItzSwirlz**
Untested as of August 1 2024 01:09 UTC.

### CODE REVIEW

**Comment by MatthewL246** [comment]
Looks good so far, just needs an update to the local environment setup.

**Comment by redmine4404** [comment]
hi, it's seem that the pikmin-3 folder is missing in the repos/ directory. In order to clone submodules, git need to have a empty directory to clone into it. Just making a directory named pikmin-3 in the repos should fix the failed checks.

**Comment by MatthewL246** [comment]
> Just making a directory named pikmin-3 in the repos should fix the failed checks.

I'd prefer adding the submodule using `git submodule add` instead of an empty directory so GitHub can track which commit the submodule is on. That should fix the checks.

**Review by MatthewL246 — APPROVED** [review]
The setup looks good to me.

**Pull request merged**
